# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-23 01:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=200, verbose_name='\u8bc4\u8bba')),
                ('add_data', models.DateField(default=datetime.datetime.now, verbose_name='\u52a0\u5165\u65f6\u95f4')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='\u8bc4\u8bba\u7684\u6587\u7ae0')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8bc4\u8bba\u7684\u7528\u6237')),
            ],
        ),
        migrations.CreateModel(
            name='UserAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u59d3\u540d')),
                ('mobile', models.CharField(max_length=20, verbose_name='\u624b\u673a')),
                ('course_name', models.CharField(max_length=20, verbose_name='\u8bfe\u7a0b\u540d\u79f0')),
                ('add_data', models.DateField(default=datetime.datetime.now, verbose_name='\u52a0\u5165\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_data', models.DateField(default=datetime.datetime.now, verbose_name='\u52a0\u5165\u65f6\u95f4')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='\u8bc4\u8bba\u7684\u6587\u7ae0')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8bc4\u8bba\u7684\u7528\u6237')),
            ],
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_id', models.IntegerField(default=0, verbose_name='\u6570\u636eid')),
                ('fav_type', models.IntegerField(choices=[(b'1', '\u8bfe\u7a0b'), (b'2', b'\xe8\xaf\xbe\xe7\xa8\x8b\xe6\x9c\xba\xe6\x9e\x84'), (b'3', b'\xe8\xae\xb2\xe5\xb8\x88')], verbose_name='\u6570\u636eid')),
                ('add_data', models.DateField(default=datetime.datetime.now, verbose_name='\u52a0\u5165\u65f6\u95f4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237')),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0, verbose_name='\u7528\u6237')),
                ('message', models.CharField(max_length=500, verbose_name='\u7528\u6237\u4fe1\u606f')),
                ('has_read', models.BooleanField(default=False, verbose_name='\u662f\u5426\u8bfb\u4e86')),
                ('add_data', models.DateField(default=datetime.datetime.now, verbose_name='\u52a0\u5165\u65f6\u95f4')),
            ],
        ),
    ]
