# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-31 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.IntegerField(choices=[(b'1', '\u8bfe\u7a0b'), (b'2', b'\xe8\xaf\xbe\xe7\xa8\x8b\xe6\x9c\xba\xe6\x9e\x84'), (b'3', b'\xe8\xae\xb2\xe5\xb8\x88')], verbose_name='\u6536\u85cf\u7c7b\u578b'),
        ),
    ]
