# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-25 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '\u8bfe\u7a0b', 'verbose_name_plural': '\u8bfe\u7a0b'},
        ),
        migrations.AlterModelOptions(
            name='courserescoure',
            options={'verbose_name': '\u8d44\u6e90', 'verbose_name_plural': '\u8d44\u6e90'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': '\u7ae0\u8282', 'verbose_name_plural': '\u7ae0\u8282'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '\u89c6\u9891', 'verbose_name_plural': '\u89c6\u9891'},
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(max_length=200, upload_to=b'image/%Y/%m', verbose_name='\u5c01\u9762\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='\u7ae0\u8282\u5305\u542b\u8bfe\u7a0b'),
        ),
    ]
