# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-29 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20170829_1330'),
        ('courses', '0002_auto_20170825_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='\u8bfe\u7a0b\u6240\u5c5e\u673a\u6784'),
        ),
    ]
