# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-23 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170823_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[(b'male', '\u5973'), (b'female', '\u7537')], default=b'female', max_length=6),
        ),
    ]
