# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-23 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170823_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='\u6682\u65f6'),
        ),
    ]
