# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-23 17:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '\u8f6e\u64ad\u56fe', 'verbose_name_plural': '\u8f6e\u64ad\u56fe'},
        ),
        migrations.AlterModelOptions(
            name='emailverifyrecord',
            options={'verbose_name': '\u90ae\u7bb1\u9a8c\u8bc1', 'verbose_name_plural': '\u90ae\u7bb1\u9a8c\u8bc1'},
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='\u53d1\u9001\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[(b'register', '\u6ce8\u518c'), (b'forget', '\u5fd8\u8bb0\u5bc6\u7801')], default=b'register', max_length=100, verbose_name='\u9a8c\u8bc1\u7801\u7c7b\u578b'),
        ),
    ]
