# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-31 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170831_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/default.png', max_length=1000, upload_to=b'image/%y/%m'),
        ),
    ]
