# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-28 16:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='catgory',
            field=models.CharField(choices=[(b'pxjg', b'\xe5\x9f\xb9\xe8\xae\xad\xe6\x9c\xba\xe6\x9e\x84'), (b'gx', b'\xe9\xab\x98\xe6\xa0\xa1'), (b'gr', b'\xe4\xb8\xaa\xe4\xba\xba')], default=datetime.datetime(2017, 8, 28, 16, 6, 15, 524296), max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='address',
            field=models.CharField(max_length=150, verbose_name='\u673a\u6784\u8be6\u7ec6\u5730\u5740'),
        ),
    ]
