# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-28 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20170828_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='category',
        ),
    ]
