# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-29 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_courseorg_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='course_nums',
            field=models.IntegerField(default=0, verbose_name=b'\xe8\xaf\xbe\xe7\xa8\x8b\xe6\x95\xb0\xe9\x87\x8f'),
        ),
        migrations.AddField(
            model_name='courseorg',
            name='students',
            field=models.IntegerField(default=0, verbose_name=b'\xe5\xad\xa6\xe4\xb9\xa0\xe4\xba\xba\xe6\x95\xb0'),
        ),
    ]
