# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-30 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20170829_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='work_year',
            field=models.IntegerField(default=0, verbose_name='\u5de5\u4f5c\u5e74\u9650'),
        ),
    ]
