# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-30 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20170830_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=b'teacher/%Y/%m', verbose_name='\u6559\u5e08\u7167\u7247'),
        ),
    ]
